# Generated by Django 3.2.20 on 2023-09-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Education', 'Education'), ('Job', 'Job'), ('Family', 'Family'), ('Culture', 'Culture'), ('Music', 'Music'), ('General', 'General')], default='General', max_length=50),
        ),
    ]
