# Generated by Django 3.2.20 on 2023-09-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='details',
            field=models.TextField(),
        ),
    ]
