# Generated by Django 3.2.20 on 2023-09-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventreview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreviews',
            name='image',
            field=models.ImageField(blank=True, default='../event_cn9ezb.jpg', upload_to='images/'),
        ),
    ]
